export const CATEGORY_ARTICLES: Record<string, () => Promise<any>> = {
  mass: () => import("@/content/mass.mdx"),
  current: () => import("@/content/current.mdx"),
  length: () => import("@/content/length.mdx"),
  area: () => import("@/content/area.mdx"),
  angle: () => import("@/content/angle.mdx"),
  pressure: () => import("@/content/pressure.mdx"),
  frequency: () => import("@/content/frequency.mdx"),
  volumeFlowRate: () => import("@/content/volumeFlowRate.mdx"),
  digital: () => import("@/content/digital.mdx"),
  temperature: () => import("@/content/temperature.mdx"),
  volume: () => import("@/content/volume.mdx"),
  energy: () => import("@/content/energy.mdx"),
  illuminance: () => import("@/content/illuminance.mdx"),
  time: () => import("@/content/time.mdx"),
  voltage: () => import("@/content/voltage.mdx"),
  power: () => import("@/content/power.mdx"),
  speed: () => import("@/content/speed.mdx"),
};